---
# Handlers for Mysql

- name: restart mysql
  command: docker restart mysql

- name: start mysql
  command: docker start mysql

- name: stop mysql
  command: docker stop mysql

- name: rm mysql
  command: docker rm mysql

- name: pull mysql
  command: docker pull mysql

- name: run mysql
  command: docker run --name mysql -v /mnt/sda1/opt/mysql:/var/lib/mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=3039762 -d mysql