---
# Handlers for Mysql

- name: restart phpmyadmin
  command: docker restart phpmyadmin

- name: start phpmyadmin
  command: docker start phpmyadmin

- name: stop phpmyadmin
  command: docker stop phpmyadmin

- name: run phpmyadmin
  command: docker run --link mysql:mysql -p 8081:80 --name=phpmyadmin  -d nazarpc/phpmyadmin